package com.liuchang.backend.global.domain.model;

public class MyUser {

    public interface UserSimpleview {};

    public interface UserDetailview extends UserSimpleview {};
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.passwd
     *
     * @mbg.generated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_user.comn_addr
     *
     * @mbg.generated
     */
    private String comnAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_id
     *
     * @return the value of my_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_id
     *
     * @param userId the value for my_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.user_name
     *
     * @return the value of my_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.user_name
     *
     * @param userName the value for my_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.passwd
     *
     * @return the value of my_user.passwd
     *
     * @mbg.generated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.passwd
     *
     * @param passwd the value for my_user.passwd
     *
     * @mbg.generated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.gender
     *
     * @return the value of my_user.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.gender
     *
     * @param gender the value for my_user.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_user.comn_addr
     *
     * @return the value of my_user.comn_addr
     *
     * @mbg.generated
     */
    public String getComnAddr() {
        return comnAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_user.comn_addr
     *
     * @param comnAddr the value for my_user.comn_addr
     *
     * @mbg.generated
     */
    public void setComnAddr(String comnAddr) {
        this.comnAddr = comnAddr == null ? null : comnAddr.trim();
    }
}