package com.jpt.icbc.ccbm.global.mapper;

import com.liuchang.backend.global.domain.model.MyUser;
import com.liuchang.backend.global.domain.model.MyUserExample;
import java.util.List;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    long countByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    int deleteByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_user
     *
     * @mbg.generated
     */
    List<MyUser> selectByExample(MyUserExample example);

}